ifeq ($(OS),Windows_NT)

    # Dossiers
    SRC_DIR = src
    BUILD_DIR = build
    BIN_DIR = bin

    # SFML
	SFML_INCLUDE = include
    SFML_LIB = lib

    # Compilateur
    CXX = g++
    CXXFLAGS = -I$(SFML_INCLUDE)
    LDFLAGS = -L$(SFML_LIB) -lsfml-graphics -lsfml-window -lsfml-system -lopengl32 -mconsole

    # Fichiers
    SRC = $(shell dir /s /b $(SRC_DIR)\*.cpp)
    OBJ = $(patsubst $(SRC_DIR)\%.cpp, $(BUILD_DIR)/%.o, $(SRC))

    # Build global
    all: compile link

    # Compilation
    compile: $(OBJ)

    $(BUILD_DIR)/%.o: $(SRC_DIR)/%.cpp
	@if not exist "$(dir $@)" mkdir "$(dir $@)"
	$(CXX) $(CXXFLAGS) -c $< -o $@

    # Link
    link:
	@if not exist "$(BIN_DIR)" mkdir "$(BIN_DIR)"
	$(CXX) $(OBJ) -o $(BIN_DIR)/main.exe $(LDFLAGS)

    # Clean
    clean:
	rmdir /s /q $(BUILD_DIR)
	rmdir /s /q $(BIN_DIR)

else

    # Dossiers
    SRC_DIR = src
    BUILD_DIR = build

    # SFML via pkg-config
    SFML_LIBS = $(shell pkg-config --libs sfml-graphics sfml-window sfml-system sfml-audio)
    SFML_CFLAGS = $(shell pkg-config --cflags sfml-graphics sfml-window sfml-system sfml-audio)

    # Compilateur
    CXX = g++
    CXXFLAGS = $(SFML_CFLAGS)

    # Fichiers
    SRC = $(wildcard $(SRC_DIR)/**/*.cpp)
    OBJ = $(patsubst $(SRC_DIR)/%.cpp, $(BUILD_DIR)/%.o, $(SRC))

    # Build global
    all: compile link

    # Compilation
    compile: $(OBJ)

    $(BUILD_DIR)/%.o: $(SRC_DIR)/%.cpp
	@mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) -c $< -o $@

    # Link
    link:
	$(CXX) $(OBJ) -o bin/main $(SFML_LIBS)

    # Clean
    clean:
	rm -rf $(BUILD_DIR) main

endif