# Détection du système d'exploitation
ifeq ($(OS),Windows_NT)
    SFML_LIBS = -Lsrc/lib -lopengl32
else
    # Utilisation de pkg-config pour récupérer les bonnes flags pour SFML
    SFML_LIBS = $(shell pkg-config --libs sfml-graphics sfml-window sfml-system sfml-audio)
    SFML_CFLAGS = $(shell pkg-config --cflags sfml-graphics sfml-window sfml-system sfml-audio)
endif

all: clean compile link

clean:
	# Nettoyage des fichiers objets
	rm -f *.o main

compile:
	# Compilation de tous les fichiers CPP avec les flags de pkg-config pour les inclure
	g++ $(SFML_CFLAGS) -c coding/*.cpp coding/States/*.cpp

link:
	# Lien des fichiers objets avec les bibliothèques SFML
	g++ *.o -o main $(SFML_LIBS)
